soxcal-2021265/La-Caja-de-Cambios

index.html
=> feat: Agregando html login

index.html
add:Agregando Seccion Para El Login
=> add:Agregando Seccion Para El Login

index.html
add: Agregando opciones de Registro
=> add: Agregando opciones de Registro

LoginHTML/Index/registro.html
add: agregando opciones de registro.html
=> add: agregando opciones de registro.html

LoginHTML/Founts/founts.css, LoginHTML/Index/MenuInicio.html, LoginHTML/Index/index.html, LoginHTML/Index/registro.html, LoginHTML/Styles/style.css
add: agregando html MenuInicio.html
=> add: agregando html MenuInicio.html

LoginHTML/Index/MenuInicio.html, LoginHTML/Index/index.html, LoginHTML/Styles/estilo.css, LoginHTML/Styles/style.css
fix: Coreccion de errores del menu inicio y css
=> fix: Coreccion de errores del menu inicio y css

LoginHTML/Index/MenuInicio.html, LoginHTML/Styles/estilo.css
feat: agregando indicador de horario
=> feat: agregando indicador de horario

LoginHTML/Index/MenuInicio.html, LoginHTML/Styles/estilo.css
refactor: Modificar el banner del MenuInicio.html
=> refactor: Modificar el banner del MenuInicio.html

LoginHTML/Index/factura.html, LoginHTML/Styles/factura.css
add: Agregando vista factura.html
=> add: Agregando vista factura.html

LaCajaDeCambios/pom.xml, LaCajaDeCambios/src/main/java/com/oscarcumatz/dominio/Cliente.java, LaCajaDeCambios/src/main/java/com/oscarcumatz/system/Principal.java, LaCajaDeCambios/src/main/resources/META-INF/persistence.xml
add: Agregando proyecto LaCajaDeCambios y mapeo auto y cliente
=> add: Agregando proyecto LaCajaDeCambios y mapeo auto y cliente

LaCajaDeCambios/pom.xml, LaCajaDeCambios/src/main/java/com/oscarcumatz/dominio/Auto.java, LaCajaDeCambios/src/main/java/com/oscarcumatz/system/Principal.java
fix: Corrigiendo archivo persistence.xml
=> fix: Corrigiendo archivo persistence.xml

JavaEE2025IN5BM/build/web/MenuInicio.jsp, JavaEE2025IN5BM/build/web/Reparaciones.jsp, JavaEE2025IN5BM/build/web/Servicio.jsp, JavaEE2025IN5BM/build/web/Styles/style.css, JavaEE2025IN5BM/build/web/index.jsp, JavaEE2025IN5BM/build/web/registro.jsp, JavaEE2025IN5BM/nbproject/private/private.properties, JavaEE2025IN5BM/web/MenuInicio.jsp, JavaEE2025IN5BM/web/Reparaciones.jsp, JavaEE2025IN5BM/web/Servicio.jsp, JavaEE2025IN5BM/web/Styles/style.css, JavaEE2025IN5BM/web/registro.jsp
add: Agregando vistas Servicio.jsp, OrdenServicio,jsp, MenuInicio.jsp, index.jsp, registro.jsp y style.css
=> add: Agregando vistas Servicio.jsp, OrdenServicio,jsp, MenuInicio.jsp, index.jsp, registro.jsp y style.css

JavaEE2025IN5BM/build/web/Accesorios.jsp, JavaEE2025IN5BM/nbproject/private/private.properties, JavaEE2025IN5BM/web/Accesorios.jsp
=> add: Agregando Accesorios.jsp

JavaEE2025IN5BM/build/web/Mecanicos.jsp, JavaEE2025IN5BM/nbproject/private/private.properties, JavaEE2025IN5BM/nbproject/project.properties, JavaEE2025IN5BM/web/Mecanicos.jsp
=> add: Agregando Mecanicos.jsp

.gitignore, LaCajaDeCambios/src/main/java/com/oscarcumatz/controller/LlantaController.java, LaCajaDeCambios/src/main/java/com/oscarcumatz/dominio/Llanta.java, LaCajaDeCambios/src/main/java/com/oscarcumatz/system/Principal.java
feat: Agregando mapeo entidad Llanta
=> feat: Agregando mapeo entidad Llanta

LoginHTML/Index/ServicioAdmin.html
add: Agregando ServicoAdmin.html
=> add: Agregando ServicoAdmin.html

JavaEE2025IN5BM/build/web/MenuInicioAdmin.jsp, JavaEE2025IN5BM/build/web/ServicioAdmin.jsp, JavaEE2025IN5BM/nbproject/private/private.properties, JavaEE2025IN5BM/web/MenuInicioAdmin.jsp, JavaEE2025IN5BM/web/ServicioAdmin.jsp
add: Agregando ServicioAdmin.jsp
=> add: Agregando ServicioAdmin.jsp

JavaEE2025IN5BM/build/web/DetalleFacturaAdmin.jsp, JavaEE2025IN5BM/nbproject/private/private.properties, JavaEE2025IN5BM/nbproject/project.properties, JavaEE2025IN5BM/web/DetalleFacturaAdmin.jsp
add: agregando DetalleFacturaAdmin.jsp
=> add: agregando DetalleFacturaAdmin.jsp

JavaEE2025IN5BM/build/web/Styles/CRUD.css, JavaEE2025IN5BM/web/Styles/CRUD.css
style: Agregando Select formato css
=> style: Agregando Select formato css

LoginHTML/Index/LlantasAdmin.html
add: agregando LlantasAdmin.html
=> add: agregando LlantasAdmin.html

LoginHTML/Index/DetalleServicioAdmin.html, LoginHTML/Index/ServicioAdmin.html
add: Agregando DetalleServicioAdmin.html
=> add: Agregando DetalleServicioAdmin.html

JavaEE2025IN5BM/build/web/DetalleServicioAdmin.jsp, JavaEE2025IN5BM/nbproject/private/private.properties, JavaEE2025IN5BM/nbproject/project.properties, JavaEE2025IN5BM/web/DetalleServicioAdmin.jsp
add: Agregando DetalleServicioAdmin.jsp
=> add: Agregando DetalleServicioAdmin.jsp

LoginHTML/Index/RepuestosAdmin.html
add: Agregando RepuestosAdmin.html
=> add: Agregando RepuestosAdmin.html

JavaEE2025IN5BM/build/web/RepuestosAdmin.jsp, JavaEE2025IN5BM/nbproject/private/private.properties, JavaEE2025IN5BM/web/RepuestosAdmin.jsp
add: Agregando RepuestosAdmin.jsp
=> add: Agregando RepuestosAdmin.jsp

LoginHTML/Index/OrdenReparacionAdmin.html, LoginHTML/Index/ReparacionesAdmin.html
Add: Agregando vistas de administrador Reparaciones.html y OrdenReparacion.html
=> Add: Agregando vistas de administrador Reparaciones.html y OrdenReparacion.html

JavaEE2025IN5BM/build/web/OrdenReparacionAdmin.jsp, JavaEE2025IN5BM/build/web/ReparacionesAdmin.jsp, JavaEE2025IN5BM/nbproject/private/private.properties, JavaEE2025IN5BM/web/OrdenReparacionAdmin.jsp, JavaEE2025IN5BM/web/ReparacionesAdmin.jsp
Add: Agregando vistas de administrador ReparacionesAdmin.jsp y OrdenReparacionAdmin.jsp
=> Add: Agregando vistas de administrador ReparacionesAdmin.jsp y OrdenReparacionAdmin.jsp

LoginHTML/Index/AccesoriosAdmin.html
add: Agregando AccesoriosAdmin.html
=> add: Agregando AccesoriosAdmin.html

JavaEE2025IN5BM/build/web/Styles/factura.css, JavaEE2025IN5BM/web/Styles/factura.css, LoginHTML/Styles/factura.css
fix: corrigiendo css conteinerBody factura.css
=> fix: corrigiendo css conteinerBody factura.css
